version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: packaroo-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - packaroo-network

  # User Service
  user-service:
    build:
      context: ./backend/services/user-service
      dockerfile: Dockerfile
    container_name: packaroo-user-service
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./backend/services/user-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/packaroo-testdb
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=kim2016
      - PORT=5001
    networks:
      - packaroo-network

  # Package Service
  package-service:
    build:
      context: ./backend/services/package-service
      dockerfile: Dockerfile
    container_name: packaroo-package-service
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./backend/services/package-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/packaroo-testdb
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=kim2016
      - PORT=5002
    networks:
      - packaroo-network

  # Delivery Service
  delivery-service:
    build:
      context: ./backend/services/delivery-service
      dockerfile: Dockerfile
    container_name: packaroo-delivery-service
    restart: always
    ports:
      - "5003:5003"
    volumes:
      - ./backend/services/delivery-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/packaroo-testdb
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=kim2016
      - PORT=5003
    networks:
      - packaroo-network

  # API Gateway
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: packaroo-api-gateway
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - user-service
      - package-service
      - delivery-service
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PACKAGE_SERVICE_URL=http://package-service:5002
      - DELIVERY_SERVICE_URL=http://delivery-service:5003
      - JWT_SECRET=kim2016
      - PORT=4000
    networks:
      - packaroo-network

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: packaroo-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=1
    networks:
      - packaroo-network

volumes:
  rabbitmq_data:

networks:
  packaroo-network:
    driver: bridge
