version: '3.1'
services:
  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - client
  server:
    image: emash90/package-server:1.0.1
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - /app/node_modules

    command: npm start
  client:
    image: emash90/package-client:1.0.4
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: npm start

